const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os');
const{createCollector}=require('../../packages/core/src/vendor/tokentracker/collector.cjs');const{normalizeToolName}=require('../../packages/core/src/vendor/tokentracker/lib/codex-rollout-parser');const{categorizeTool}=require('../../packages/core/src/vendor/tokentracker/lib/categorizer-utils');
const meta={type:'session_meta',payload:{id:'fixture',cwd:'/tmp'}};
const usage=(id,total)=>({type:'event_msg',timestamp:'2026-09-06T04:52:'+String(total).padStart(2,'0')+'Z',payload:{type:'token_count',turn_id:id,info:{total_token_usage:{input_tokens:total,output_tokens:0,total_tokens:total},last_token_usage:{input_tokens:10,output_tokens:0,total_tokens:10}}}});
const settings=model=>({type:'event_msg',payload:{type:'thread_settings_applied',thread_settings:{model}}});
async function collect(rows){const home=await fs.mkdtemp(path.join(os.tmpdir(),'ar-model-test-'));try{const dir=path.join(home,'.codex/sessions/2026/09/06');await fs.mkdir(dir,{recursive:true});await fs.writeFile(path.join(dir,'rollout-fixture.jsonl'),[meta,...rows].map(JSON.stringify).join('\n')+'\n');const c=createCollector({home,fetchImpl:async()=>{throw Error('offline')}});await c.sync(true);const r=await c.query('/functions/tokentracker-usage-model-breakdown',{from:'2026-09-06',to:'2026-09-06',tz:'UTC'});return r.sources[0]?.models||[]}finally{await fs.rm(home,{recursive:true,force:true})}}
test('MCP namespace separator supports split, trailing separator and already qualified names',()=>{for(const payload of [{namespace:'mcp__cua_repl',name:'js'},{namespace:'mcp__cua_repl__',name:'js'},{namespace:'mcp__cua_repl',name:'mcp__cua_repl__js'}]){assert.equal(normalizeToolName(payload),'mcp__cua_repl__js');assert.equal(categorizeTool(normalizeToolName(payload)),'MCP: cua-repl')}});
test('usage preceding the only session model is recovered from nested thread settings',async()=>{const m=await collect([usage(null,10),settings('gpt-6-astra')]);assert.equal(m[0].model,'gpt-6-astra');assert.equal(m[0].totals.total_tokens,10)});
test('multiple future models stay unknown without a unique turn match',async()=>{const m=await collect([usage(null,10),settings('model-a'),settings('model-b')]);assert.equal(m[0].model,'unknown')});
test('a unique turn model resolves earlier usage even when the session has multiple models',async()=>{const m=await collect([usage('turn-a',10),{type:'turn_context',payload:{turn_id:'turn-a',model:'model-a'}},settings('model-b')]);assert.equal(m[0].model,'model-a')});
test('settings switches apply forward while an explicit in-flight turn retains its model',async()=>{const m=await collect([{type:'turn_context',payload:{turn_id:'turn-a',model:'model-a'}},settings('model-b'),usage('turn-a',10),{type:'event_msg',payload:{type:'task_started',turn_id:'turn-b'}},usage('turn-b',20)]);assert.deepEqual(new Map(m.map(x=>[x.model,x.totals.total_tokens])),new Map([['model-a',10],['model-b',10]]))});
test('old unknown buckets are replaced once without changing totals or raw sessions',async()=>{
 const home=await fs.mkdtemp(path.join(os.tmpdir(),'ar-model-migrate-'));try{
 const dir=path.join(home,'.codex/sessions/2026/09/06');await fs.mkdir(dir,{recursive:true});const file=path.join(dir,'rollout-fixture.jsonl');const raw=[meta,usage(null,10),settings('gpt-6-astra')].map(JSON.stringify).join('\n')+'\n';await fs.writeFile(file,raw);
 const options={home,fetchImpl:async()=>{throw Error('offline')}};const c=createCollector(options);await c.sync(true);const data=path.join(home,'.agentrouter/collector'),cp=path.join(data,'cursors.json'),qp=path.join(data,'queue.jsonl');const cursors=JSON.parse(await fs.readFile(cp));delete cursors.arModelSchema;await fs.writeFile(cp,JSON.stringify(cursors));const rows=(await fs.readFile(qp,'utf8')).trim().split('\n').map(JSON.parse);for(const r of rows)if(r.source==='codex')r.model='unknown';await fs.writeFile(qp,rows.map(JSON.stringify).join('\n')+'\n');
 const restarted=createCollector(options);await restarted.sync(true);const once=await fs.readFile(qp,'utf8');assert(!once.includes('"unknown"'));await restarted.sync(true);assert.equal(await fs.readFile(qp,'utf8'),once);assert.equal(await fs.readFile(file,'utf8'),raw);assert.equal(JSON.parse(await fs.readFile(cp)).arModelSchema,2);
 // An unavailable original must not erase already collected history.
 const state=JSON.parse(await fs.readFile(cp));delete state.arModelSchema;await fs.writeFile(cp,JSON.stringify(state));await fs.unlink(file);await assert.rejects(createCollector(options).sync(true),/would lose usage/);assert.equal(await fs.readFile(qp,'utf8'),once);
 }finally{await fs.rm(home,{recursive:true,force:true})}
});
