export const memoryCopyZh: Record<string, string> = {
  "Project memory": "项目记忆",
  "Memories": "记忆",
  "Default workspace": "默认工作区",
  "Default project": "默认项目",
  "Project details": "项目详情",
  "Project content": "项目内容",
  "Search results": "搜索结果",
  "Service settings": "服务设置",
  "Advanced maintenance": "高级维护",
  "Memory directory": "记忆目录",
  "No memories yet": "还没有记忆",
  "Select a memory to read": "选择一条记忆",
  "Browse this project's memories in the directory.": "从左侧目录查看这个项目的记忆。",
  "Connect client": "接入客户端",
  "No matching memories.": "没有找到匹配的记忆。",
  "Memory service": "记忆服务",
  "Project connection": "项目接入",
  "Choose which project to capture. Project instructions guide the agent to retrieve memory; skills provide the detailed workflow.": "选择允许采集的项目，安装记忆检索指令和配套 Skills。",
  "Project files configured": "项目文件已配置",
  "Project files changed": "项目文件已变更",
  "Project directory": "项目目录",
  "Project name": "项目名称",
  "Instruction format": "客户端指令格式",
  "Preview project connection": "预览接入内容",
  "Apply these project files to enable capture and startup briefings. Existing instructions are preserved; changed files are backed up.": "确认以下项目文件。新项目将启用采集和启动简报；已有项目保留原有采集与简报设置。原有指令会保留，修改前会备份。",
  "Will update": "待更新",
  "Unchanged": "无变化",
  "Enable project memory": "启用项目记忆",
  "Project configured. Connect the client below, then start a new session in this directory.": "项目已配置。在下方接入客户端，然后在此目录启动新会话。",
  "Client connection": "客户端接入",
  "ZCode has no session-end event. Finish the session from Project memory > Sessions after your work is complete.": "ZCode 没有会话结束事件。工作结束后，在「项目记忆 → 会话」中完成收尾，生成记忆和交接。",
  "MiMo automatically captures completed turns and recalls them in new conversations.": "MiMo 自动采集已完成的对话轮次，新对话自动读取，无需手动收尾。",
  "This client retrieves handoffs through MCP; startup hook output is not injected.": "此客户端通过 MCP 读取交接内容，不支持启动 Hook 自动注入。",
  "Finish this session and generate its memory and handoff? Only continue after the client has finished working.": "结束此会话并生成记忆和交接？请确认客户端已完成本次工作。",
  "Finish session": "完成收尾",
  "Memory organization": "记忆整理",
  "Capture and session pages work without a model. Model review extracts reusable knowledge; scheduled cleanup and checks run locally.": "采集和会话记忆无需模型。模型审查可提炼长期经验；定期清理与检查在本地运行。",
  "No model override saved. Advanced TOML settings remain in effect.": "尚未保存独立模型设置，当前使用高级配置。",
  "Stop memory before editing model settings.": "修改模型前请先停止记忆服务。",
  "Use a model to organize memory": "启用模型整理",
  "OpenAI-compatible API URL": "OpenAI 兼容 API 地址",
  "Model name": "模型名称",
  "Saved; leave blank to keep for the same API URL": "已保存；地址不变时留空保留",
  "Optional for local models": "本地模型可留空",
  "Clear saved API key": "清除已保存的 API Key",
  "Organize each completed session": "会话结束后整理内容",
  "Review completed sessions in the background": "后台定期提炼已结束会话",
  "Require approval before applying proposed edits": "记忆修改需人工批准",
  "Save model settings": "保存模型设置",
  "Test saved model": "测试已保存模型",
  "Review cadence and thresholds follow advanced configuration. Review proposals in Advanced maintenance. These model settings override the corresponding TOML fields.": "审查周期和门槛沿用高级配置。在「高级维护」中查看和批准提案；此处保存的模型设置优先于 TOML 中对应字段。",
  "Save memory model settings? Enabled model tasks send captured project content to this API and may incur charges. Changes take effect on next start.": "保存记忆模型设置？启用后，整理任务会把采集内容发送至此 API，可能产生模型费用。下次启动生效。",
  "Send a small structured test request to the saved model? This may incur a model charge.": "向已保存模型发送一次简短的结构化测试请求？可能产生模型费用。",
  "Model connection and structured response verified.": "模型连接和结构化响应验证通过。",
  "Memory": "记忆",
  "Knowledge": "知识库",
  "Handoffs": "交接",
  "Clients": "客户端",
  "Maintenance": "维护",
  "Projects": "项目",
  "Pages": "记忆页面",
  "Data directory": "数据目录",
  "Memory sections": "记忆功能",
  "Select project": "选择项目",
  "Connect your coding clients to project memory.": "连接编程客户端，共享项目记忆。",
  "Read and write memory": "读写记忆",
  "Capture sessions": "采集会话",
  "Configuration files": "配置文件",
  "Enable capture for a project": "如何开启项目采集",
  "Session capture requires a .ai-memory.toml file in the project root with its workspace and project names. Reload the client after connecting.": "在项目根目录的 .ai-memory.toml 中填写工作空间和项目名称后，才会采集该项目。接入后请重启客户端。",
  "Project": "项目",
  "workspace": "工作空间",
  "project": "项目",
  "path": "页面路径",
  "stopped": "已停止",
  "starting": "启动中",
  "running": "运行中",
  "stopping": "停止中",
  "error": "运行异常",
  "unavailable": "暂不可用",
  "Loading": "加载中",
  "Start memory": "启动记忆",
  "Stop memory": "停止记忆",
  "Shared knowledge, session history, and handoffs across coding clients.": "跨客户端共享项目知识、会话历史与任务交接。",
  "New memory": "新建记忆",
  "Edit memory": "编辑记忆",
  "Memory content": "记忆内容",
  "Pinned": "固定保留",
  "Memory saved.": "记忆已保存。",
  "No memory pages yet. Connect a client or create a memory.": "还没有记忆。接入客户端开始积累，或手动创建一条。",
  "Search memory": "搜索记忆",
  "Search decisions, errors, and previous work": "搜索决策、错误和历史工作",
  "No handoffs in this project.": "这个项目还没有交接记录。",
  "This handoff is private.": "这条交接记录不可见。",
  "Client-wide configuration. Agent profiles are not changed. Automatic capture requires a project allowlist marker.": "按客户端管理，不修改 Agent 配置档案。仅采集带有项目白名单标记的目录。",
  "Configured · reload client": "已配置 · 请重载客户端",
  "Not configured or changed": "未配置或配置已变更",
  "Connect": "接入",
  "Disconnect": "移除接入",
  "Apply client configuration?": "确认修改客户端配置？",
  "Remove client integration?": "确认移除客户端接入？",
  "Other client settings and memory data are preserved.": "保留其他客户端设置和已存储的记忆。",
  "Configuration saved. Reload the client, then verify capture with a real session.": "配置已写入。重载客户端后，请通过真实会话验证采集是否生效。",
  "Opt in a project with .ai-memory.toml in its root. Use explicit workspace and project names.": "在项目根目录放置 .ai-memory.toml 可允许采集。请明确指定工作空间和项目名。",
  "All bundled memory operations remain available. Review the scope and parameters before applying changes.": "管理检索、整理、去重、记忆版本与交接。执行前请核对作用范围和参数。",
  "Memory operation": "记忆操作",
  "Apply memory operation?": "确认执行记忆操作？",
  "This may modify stored memory or use the configured model.": "此操作可能修改记忆，或调用已配置的模型。",
  "Start memory with AgentRouter": "随 AgentRouter 启动记忆",
  "Semantic search": "语义检索",
  "Enable semantic search? The default local provider downloads a model once. A cloud embedding provider in advanced configuration sends memory content to that provider.": "启用语义检索？默认使用本地模型，首次需要下载。如果高级配置选择了云端向量模型，记忆内容会发送给对应供应商。",
  "Stop memory before changing models or configuration. Cloud providers require an explicit configuration change.": "修改模型或配置前需停止记忆服务。云端模型仅在明确配置后使用。",
  "Back up memory": "备份记忆",
  "Backup saved": "备份已保存",
  "Advanced configuration": "高级配置",
  "Load": "读取",
  "Save configuration": "保存配置",
  "Save memory configuration? A backup is kept. Provider settings may enable external model calls on next start.": "确认保存记忆配置？旧配置会备份。供应商设置可能在下次启动后启用外部模型调用。",
  "Configuration saved. Changes take effect on next start.": "配置已保存，下次启动时生效。",
  "Service log": "服务日志",
  "No log entries.": "暂无日志。",
  "Memory runtime is missing": "记忆运行组件缺失",
  "Your project memory, in one place": "项目记忆，集中管理",
  "This build does not contain the memory runtime. Rebuild or reinstall AgentRouter.": "当前构建缺少记忆组件，请重新构建或安装 AgentRouter。",
  "Start memory to browse knowledge and connect your coding clients. No projects are captured until you opt in.": "启动后可浏览知识库并接入编程客户端。项目采集默认不开启。",
  "No captured sessions in this project.": "这个项目还没有采集到会话。",
  "events": "条事件",
  "Previous": "上一页",
  "Next": "下一页",
  "Default": "默认",
  "Run operation": "执行操作",
  "Check the structured parameter format.": "请检查结构化参数格式。",
  "Structured arguments": "结构化参数",
  "Use JSON arguments": "使用 JSON 参数"
};
