// Generated by build/brand.mjs from build/brand.json.
enum AppBrand {
 static let name = "AgentRouter"
 static let appId = "com.agentrouter.desktop"
 static let website = "https://zhangqinzhong.com/AgentRouter/"
 static let repository = "https://github.com/zhangqinzhong/AgentRouter"
 static let iconFile = "app-icon.icns"
}
